spring:
  application:
    name: bank-app

  datasource:
    url: jdbc:mysql://localhost:3306/banking_app
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
